**在数组题完成了132/198后，开始继续按照算法分类来做题，这个notebook用来记录动态规划的算法题，动态规划是非常重要的一种算法**

# NO.139 单词拆分

给定一个字符串s和一个单词列表wordDict，判断字符串能否由列表中的单词组成；  
一开始是想从头开始遍历，当遍历过的字符串在列表中，就从该位置继续向后找，但是如果这样计算：   
对于字符串`aaaaaaa`，单词列表`[aaa,aaaa]`，会将其分为`aaa aaa a`；  
因此考虑用动态规划来做，dp[i]表示s的前i个元素组成的字符串能否由列表里的单词组成；  
计算dp[i]的时候，需要从头开始遍历，有两种情况：  
1.s[:i+1]是一个单词，则令dp[i]=1；  
2.位置i的前面有一个可由单词组成的字符串s[:j+1]，则只要判断s[i+1:j+1]是否是一个单词，如果满足，令dp[i]=1；  

In [3]:
s = "catsandog"
wordDict = ["cats", "dog", "sand", "and", "cat"]

dp = [0 for i in s]
dp[0] = 1 if s[0] in wordDict else 0
for i in range(1,len(dp)):
    for j in range(i):
        if s[:i+1] in wordDict:
            dp[i] = 1
            break
        elif dp[j]==1 and s[j+1:i+1] in wordDict:
            dp[i] = 1
            break

print(dp)
print(dp[-1]==1)

[0, 0, 1, 1, 0, 0, 1, 0, 0]
False


# NO.221 最大正方形

给定的一个二维矩阵matrix中只包含字符0和1，要找到里面由1组成的最大的正方形的面积；  
既然是动态规划类里面的题目，一开始就没考虑其他方法，所以就只要定义dp数组并找到更新dp的方式就行了；  
定义dp[i][j]表示matrix中以[i,j]作为左上角的正方形的最大面积，因此，如果matrix[i][j]为0，那么dp[i][j]就为0，如果matrix[i][j]为1，那么就看dp[i+1][j+1]的值：  
如果dp[i+1][j+1]的值为a，则表示一个面积为a的正方形，那么边长为l=$\sqrt{a}$，因此在求dp[i][j]的值时，需要判断matrix[i:i+l][j]和matrix[i][j:j+l]中最长边（不含0）的长度；
$$
  \begin{matrix}
   1 & 1 & 1 & 1 \\
   1 & 1 & 1 & 1 \\
   0 & 1 & 1 & 1 \\
   1 & 1 & 1 & 1
  \end{matrix} \tag{1}
$$
对于上面的例子，加入已经求出来dp[1][1]==9，在求dp[0][0]的时候，matrix[i:i+l][j]和matrix[i][j:j+l]中最长边为2，也就是以matrix[0][0]为左上角的正方形的最大面积为4（一开始想错了，以为没有找到l+1的边就将dp[0][0]置为1）

一开始处理变量的时候考虑了变量复制里面传值和传地址和深浅拷贝的问题：
>在python中对静态变量（字符串，数值，元组）的传递是拷贝（首次传递是引用），对动态变量（列表，字典）的传递为引用；  
>浅拷贝：只拷贝父对象，不拷贝内部的子对象，如：copy.copy()；  
>深拷贝：完全拷贝父对象及其子对象，如：copy.deepcopy()；    


In [147]:
import numpy as np
import copy

matrix = [["1","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","0","0","1","1","1","1","1","1","1","1","0","0","1","1","1","0","1","1","1","1","1","1","1","1"],["1","1","1","1","0","1","1","0","1","1","1","1","1","1","1","1","1","0","1","1","0","1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1"],["0","1","1","1","1","0","1","0","1","1","1","1","1","1","0","1","1","0","1","1","0","1","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1"],["0","1","0","1","1","0","1","0","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1","1","0","1","0","1","1","0","1","1","1","1","1","1"],["1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","0","1","1","0","0","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1"],["1","1","1","1","1","1","1","1","1","0","1","1","0","1","0","1","1","1","1","1","1","1","1","1","1","1","0","1","0","1","1","1","1","1","1","0","1","1","1","1"],["0","1","1","0","1","1","0","1","0","1","1","1","0","0","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","0","1","0","1"],["0","1","1","1","1","1","1","1","1","1","1","1","1","1","0","0","1","1","1","1","1","1","1","0","0","1","1","0","0","1","1","0","1","1","0","1","0","1","0","1"],["1","1","1","1","0","1","1","1","1","0","1","1","1","1","1","1","1","1","1","0","1","1","0","1","1","0","1","1","1","1","0","1","0","1","1","0","1","0","1","1"],["1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1","0","1","1","0","1","1","0","1","1","1","0","1","1","1","1","0","1","1","1","1"],["1","1","1","0","1","1","0","0","1","1","1","1","1","1","1","1","1","1","1","1","0","0","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1"],["1","0","1","1","1","1","1","1","1","0","1","1","1","1","0","1","1","1","1","0","0","1","1","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1"],["0","1","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1","0","1","1","1","0","1","1","1","1","1","0","1","1","1","1","1"],["1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1","0","1","1"],["1","1","1","1","1","0","0","1","1","1","1","1","1","1","1","0","1","0","1","1","0","0","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1"],["1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1"],["1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","0","0","1","1","1","1","1","1","0","0","1","1","1","1","1"],["1","1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","0","1","1","1"],["1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","0","1","1","1","1","1","0","0","1","0","1","1","1","1","1","0","1","1","1","1","1","1"],["1","1","1","1","1","1","0","0","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1"],["1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","0","1","1","1","1","1","0","1","1","1","1","1","0","1","1","0","1","1"],["1","1","0","0","0","1","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1","1"],["1","1","1","1","1","0","1","0","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","0","0","1","0","1","1","1","0","0","1","1","1","1","1","1","1","1"],["1","1","1","0","0","1","0","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","0","1","1","1","1","0","1","1","1","1","0","1","1","1","1","1","0","1"],["1","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","0","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1"],["1","1","1","1","1","1","1","0","1","1","1","1","1","1","0","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1"],["1","1","1","0","0","1","1","1","1","1","1","1","1","1","1","0","1","1","1","0","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","0","1","1","1"],["1","1","1","1","1","1","1","1","1","1","1","1","1","1","0","0","1","1","1","1","1","1","0","1","0","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1"],["1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","0","0","0","1","1","1","1","1","1","1","1","1","0","1","1","1","0","1"],["1","1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","0","0","1","1","1","0","1","1","0","1","1"],["1","1","1","1","0","1","1","0","1","1","1","1","1","1","0","1","1","0","1","1","0","1","1","1","1","1","1","0","1","1","1","1","1","1","1","0","1","1","1","1"],["1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1"],["1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1"],["1","1","0","0","0","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1","1","0","1","1"],["1","1","1","1","1","0","1","1","1","1","1","1","1","1","0","1","1","1","1","0","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1"],["0","1","1","1","1","1","1","1","1","1","1","1","0","0","1","1","1","1","1","1","1","1","1","1","0","1","0","1","0","1","1","0","1","1","1","1","1","1","1","1"],["1","0","1","1","0","1","1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1","1","1","0","0","1","1"],["1","0","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","0","0","1","1","1","1","1"],["0","1","1","1","1","0","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1","1","1","1"],["0","1","1","1","1","1","1","0","1","1","1","1","1","1","1","1","0","1","1","1","0","1","1","1","1","0","1","1","1","0","1","1","1","1","1","1","1","1","1","1"],["0","1","1","1","1","1","1","1","1","1","1","1","0","1","0","1","1","1","1","0","1","1","1","1","1","1","0","1","0","1","1","0","0","1","1","1","1","0","1","1"],["1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","0","1","1","1","1","1","1","1","0","1","1","1","1","1","1","1","1","0","1","1","1","0"],["1","1","1","1","1","0","1","1","1","1","1","1","1","1","0","0","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1","0","0","1","1","1","1"],["1","1","0","1","1","0","1","1","1","1","1","1","0","1","0","1","1","1","1","1","0","1","1","1","1","1","1","1","1","0","0","1","1","1","0","1","0","1","0","0"],["0","1","1","0","1","1","1","1","1","1","1","0","0","1","1","1","1","1","0","0","1","0","1","1","1","1","1","0","1","1","1","0","1","1","0","1","1","1","0","1"]]
dp = [[int(i) for i in l] for l in matrix]
# matrix = [[int(i) for i in l] for l in matrix]
matrix = dp.copy()

for i in range(len(matrix)-2,-1,-1):
    for j in range(len(matrix[0])-2,-1,-1):
        if matrix[i][j]==0:
            dp[i][j] = 0
        else:
            l = int(dp[i+1][j+1]**0.5)
            sign = 0
            for n in range(1,l+1):
                if dp[i+n][j]==0 or dp[i][j+n]==0:
                    sign = 1
                    break
            if sign:
                dp[i][j] = n**2
            else: dp[i][j] = (l+1)**2

maxm = max([max(l) for l in dp]) if dp else 0
print(maxm)

64


再一次被评论区大佬按在地上摩擦。。。   
计算dp[i][j]的方法可以再简化，可以根据求min(dp[i+1][j+1],dp[i][j+1],dp[i+1][j])可以计算dp[i][j]

In [154]:
import numpy as np
import copy

matrix = [["1","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","0","0","1","1","1","1","1","1","1","1","0","0","1","1","1","0","1","1","1","1","1","1","1","1"],["1","1","1","1","0","1","1","0","1","1","1","1","1","1","1","1","1","0","1","1","0","1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1"],["0","1","1","1","1","0","1","0","1","1","1","1","1","1","0","1","1","0","1","1","0","1","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1"],["0","1","0","1","1","0","1","0","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1","1","0","1","0","1","1","0","1","1","1","1","1","1"],["1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","0","1","1","0","0","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1"],["1","1","1","1","1","1","1","1","1","0","1","1","0","1","0","1","1","1","1","1","1","1","1","1","1","1","0","1","0","1","1","1","1","1","1","0","1","1","1","1"],["0","1","1","0","1","1","0","1","0","1","1","1","0","0","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","0","1","0","1"],["0","1","1","1","1","1","1","1","1","1","1","1","1","1","0","0","1","1","1","1","1","1","1","0","0","1","1","0","0","1","1","0","1","1","0","1","0","1","0","1"],["1","1","1","1","0","1","1","1","1","0","1","1","1","1","1","1","1","1","1","0","1","1","0","1","1","0","1","1","1","1","0","1","0","1","1","0","1","0","1","1"],["1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1","0","1","1","0","1","1","0","1","1","1","0","1","1","1","1","0","1","1","1","1"],["1","1","1","0","1","1","0","0","1","1","1","1","1","1","1","1","1","1","1","1","0","0","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1"],["1","0","1","1","1","1","1","1","1","0","1","1","1","1","0","1","1","1","1","0","0","1","1","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1"],["0","1","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1","0","1","1","1","0","1","1","1","1","1","0","1","1","1","1","1"],["1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1","0","1","1"],["1","1","1","1","1","0","0","1","1","1","1","1","1","1","1","0","1","0","1","1","0","0","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1"],["1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1"],["1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","0","0","1","1","1","1","1","1","0","0","1","1","1","1","1"],["1","1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","0","1","1","1"],["1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","0","1","1","1","1","1","0","0","1","0","1","1","1","1","1","0","1","1","1","1","1","1"],["1","1","1","1","1","1","0","0","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1"],["1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","0","1","1","1","1","1","0","1","1","1","1","1","0","1","1","0","1","1"],["1","1","0","0","0","1","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1","1"],["1","1","1","1","1","0","1","0","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","0","0","1","0","1","1","1","0","0","1","1","1","1","1","1","1","1"],["1","1","1","0","0","1","0","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","0","1","1","1","1","0","1","1","1","1","0","1","1","1","1","1","0","1"],["1","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","0","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1"],["1","1","1","1","1","1","1","0","1","1","1","1","1","1","0","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1"],["1","1","1","0","0","1","1","1","1","1","1","1","1","1","1","0","1","1","1","0","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","0","1","1","1"],["1","1","1","1","1","1","1","1","1","1","1","1","1","1","0","0","1","1","1","1","1","1","0","1","0","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1"],["1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","0","0","0","1","1","1","1","1","1","1","1","1","0","1","1","1","0","1"],["1","1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","0","0","1","1","1","0","1","1","0","1","1"],["1","1","1","1","0","1","1","0","1","1","1","1","1","1","0","1","1","0","1","1","0","1","1","1","1","1","1","0","1","1","1","1","1","1","1","0","1","1","1","1"],["1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1"],["1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1"],["1","1","0","0","0","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1","1","0","1","1"],["1","1","1","1","1","0","1","1","1","1","1","1","1","1","0","1","1","1","1","0","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1"],["0","1","1","1","1","1","1","1","1","1","1","1","0","0","1","1","1","1","1","1","1","1","1","1","0","1","0","1","0","1","1","0","1","1","1","1","1","1","1","1"],["1","0","1","1","0","1","1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1","1","1","0","0","1","1"],["1","0","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","0","0","1","1","1","1","1"],["0","1","1","1","1","0","1","1","1","1","0","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1","1","1","1"],["0","1","1","1","1","1","1","0","1","1","1","1","1","1","1","1","0","1","1","1","0","1","1","1","1","0","1","1","1","0","1","1","1","1","1","1","1","1","1","1"],["0","1","1","1","1","1","1","1","1","1","1","1","0","1","0","1","1","1","1","0","1","1","1","1","1","1","0","1","0","1","1","0","0","1","1","1","1","0","1","1"],["1","1","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","0","1","1","1","1","1","1","1","0","1","1","1","1","1","1","1","1","0","1","1","1","0"],["1","1","1","1","1","0","1","1","1","1","1","1","1","1","0","0","1","1","1","1","1","1","1","1","1","1","1","0","1","1","1","1","1","1","0","0","1","1","1","1"],["1","1","0","1","1","0","1","1","1","1","1","1","0","1","0","1","1","1","1","1","0","1","1","1","1","1","1","1","1","0","0","1","1","1","0","1","0","1","0","0"],["0","1","1","0","1","1","1","1","1","1","1","0","0","1","1","1","1","1","0","0","1","0","1","1","1","1","1","0","1","1","1","0","1","1","0","1","1","1","0","1"]]
dp = [[int(i) for i in l] for l in matrix]
matrix = [[int(i) for i in l] for l in matrix]

for i in range(len(matrix)-2,-1,-1):
    for j in range(len(matrix[0])-2,-1,-1):
        if matrix[i][j]!=0:
            l = int(min(dp[i+1][j+1],dp[i+1][j],dp[i][j+1])**0.5)
            dp[i][j] = (l+1)**2
maxm = max([max(l) for l in dp]) if dp else 0
print(maxm)

64


# NO.264 丑数II

丑数是只包含质因数2，3，5的正整数，也就是可以分解为2，3，5的乘积，从1开始有：1，2，3，4，5，6，8，9，10，12，15...,求第n个丑数

**方法一：**对于每一个数，如果其整除2，3，5的结果存在与之前的序列，那么该数就是一个丑数，但是这样做超时

In [159]:
n = 100

L = [1,2,3,4,5]
if n <= 5:
    print(n)
i = 6
while len(L) < n:
    if i%2==0 and i//2 in L:
        L.append(i)
    elif i%3==0 and i//3 in L:
        L.append(i)
    elif i%5==0 and i//5 in L:
        L.append(i)
    i += 1
print(L[-1])

1536


**方法二：**使用hash表对方法一的查找判断进行优化,结果还是超时

In [161]:
n = 100

count = 5
dic = {1:1,2:1,3:1,4:1,5:1}
if n <= 5:
    print(n)
i = 6
while count < n:
    if i%2==0 and dic[i//2]==1:
        dic[i] = 1
    elif i%3==0 and dic[i//3]==1:
        dic[i] = 1
    elif i%5==0 and dic[i//5]==1:
        dic[i] = 1
    else: dic[i] = 0
    if dic[i]==1:
        count += 1
    i += 1
print(i-1)

1536


**方法三：**换一种思路，不去判断一个数是不是丑数，而是根据已知的丑数来计算下一个丑数；  
每一个丑数肯定是之前的丑数乘上2或3或5得到，并且要是从小到大的顺序，因此，可以使用三个指针p2，p3，p5分别指向将要乘以2，3，5的位置，如果乘以2是三者之间的最小值，那么将p2加一，依次进行

In [162]:
L = [1]
p2,p3,p5 = 0,0,0
for i in range(n-1):
    L.append(min(L[p2]*2,L[p3]*3,L[p5]*5))
    if L[-1]==L[p2]*2:
        p2 +=1
    if L[-1]==L[p3]*3:
                p3 += 1
    if L[-1]==L[p5]*5:
        p5 += 1
print(L[-1])

1536


# NO.279 完全平方数

给定一个正整数n，其可以表示为多个完全平方数的和，求完全平方数的最少个数；  
**方法一：动态规划：**dp[i]表示可以组成第i个数的完全平方数的个数，因为每个数都可以表示为1的和，因此将dp[i]初始化为i（dp从0开始），dp数组的更新公式：  
$$dp[i]=min(dp[i],dp[i-j*j]+1)$$  
也就是，第i个数n可以表示为1+(n-1)，此时n的完全平方数个数就等于dp[n-1]+1，同理，n也可以表示为4+(n-4)，表示n的完全平方数的个数就为dp[n-4]+1，依次进行，直到i-j*j<0;  
python3写的动态规划超时，但是评论说java就没有超时。。。

In [13]:
n = 43

dp = [n for i in range(n+1)]
dp[0] = 0
for i in range(1,n+1):
    j = 1
    while i-j*j >= 0:
        dp[i] = min(dp[i],dp[i-j*j]+1)
        j += 1
print(dp[-1])

3


**方法二：四数平方和定理：**先使用推论减小数的大小，然后判断是不是只能由四个整数平方和组成，再判断两个整数平方和的情况，如果都不满足就是三个整数平方和

>**四平方数和定理：每个正整数均可表示为四个整数的平方和（可以包含0）；**   
>**四平方数和定理的推论：满足四平方数和定理的数n（由四个非零整数的平方和构成），必定满足$n=4^a(8b+7)$；**

In [1]:
n = 213681

def numSquares(n):
    while n%4==0:
        n = n//4
    if n%8==7:
        return 4
    j = 0
    while n-j*j>0:
        k = int((n-j*j)**0.5)
        if j*j+k*k==n:
            return (j!=0) + (k!=0)
        j += 1
    return 3

numSquares(n)

3

# NO.300 最长上升子序列

给定一个数组nums，求里面长度最长的严格递增子序列，子序列不要求连续；  
一开始想的话没有什么好一点的方法，但是如果想到了使用动态规划就非常简单了，令dp[i]表示以nums[i]结尾的最长递增子序列，则有递推公式：  
$$dp[i]=max(dp[i],dp[j]+1),j=0,1,...,j-1$$
最终的结果就是dp数组的最大值

In [9]:
nums = [10,9,2,5,3,7,101,18]

if not nums:
    print(0)
dp = [1 for i in range(len(nums))]
for i in range(1,len(nums)):
    for j in range(i):
        if nums[i]>nums[j]:
            dp[i] = max(dp[i],dp[j]+1)
print(max(dp))

4


用动态规划求解的时间复杂度是$O(n^2)$，还有另外一种解法是二分查找法，时间复杂度是$O(nlog^n)$

# NO.322 零钱兑换

给定不同金额的硬币coins和一个总金额amount，求最少能够兑换的硬币个数，如果不能兑换返回-1；  
考虑使用动态规划进行求解，用dp[i]表示金额i能够兑换coins的最少个数，计算dp[i]的公式为:  
$$dp[i]=min(dp[i-coins[j]]+1)$$
即当前的dp[i]可以由之前计算的结果得到，这也正是动态规划的思想，coins里的每一个值j表示一个硬币，i可以由j和i-j兑换得到，其中dp[j]=1，因此只需要知道dp[i-j]就可以求出dp[i]

In [10]:
coins = [2,3,5]
amount = 183423

def coinChange(coins, amount):
    dp = [float('inf') for i in range(amount+1)]
    dp[0] = 0
    for i in range(1,len(dp)):
        for c in coins:
            if i>=c:
                dp[i] = min(dp[i],dp[i-c]+1)
    return dp[-1] if dp[-1]!=float('inf') else -1

coinChange(coins, amount)

36685

# NO.1035 不相交的线

给定两个数组A和B，每个数组里的数表示一条直线上的点，两条线上相同的点可以连成一条直线，要求直线之间不相交，求直线的最大数量；  
好像是在5个月前的周赛里见过这道题，当时没写出来，好吧，现在还是没想出来；  
看了一下评论区大佬的解法，才发现这就是一道普通的动态规划题，dp方程可以描述为:   

$$
dp[i][j]=
\begin{cases}
max(dp[i+1][j],dp[i][j+1]), &if\ \ A[i]!=B[j] \\
dp[i+1][j+1]+1, &if\ \ A[i]==B[j]
\end{cases}
$$

dp[i][j]表示A[i:]和B[j:]之间连线的数量，如果当前的A[i]和B[j]相等，dp[i][j]就等于后面的dp[i+1][j+1]加上1，否则就是max(dp[i+1][j],dp[i][j+1])   
求解的过程就是从A和B的最后一个位置开始向前遍历，使用dp方程更新一个dp数组，然后取数组的最大值；   
dp虽然感觉看懂了，但是真正实现起来还是一堆的问题，所以还是要多练练

In [4]:
import numpy as np

A = [1,3,7,1,7,5]
B = [1,9,2,5,1]

dp = [[0 for i in range(len(B)+1)] for j in range(len(A)+1)]
print(np.array(dp))
for i in range(len(A)-1,-1,-1):
    for j in range(len(B)-1,-1,-1):
        if A[i]==B[j]:
            dp[i][j] = dp[i+1][j+1]+1
        else:
            dp[i][j] = max(dp[i+1][j],dp[i][j+1])
print(np.array(dp))
print(dp[0][0])

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[2 1 1 1 1 0]
 [2 1 1 1 1 0]
 [2 1 1 1 1 0]
 [2 1 1 1 1 0]
 [1 1 1 1 0 0]
 [1 1 1 1 0 0]
 [0 0 0 0 0 0]]
2


其实这题和 NO.1143:最长公共子序列 这道题是一模一样的，只不过这里做了一下包装，将相等的元素描述为连线，所以关键还是要看到问题的本质

# NO.1143 最长公共子序列

NO.1035:不相交的线 找过来的，这两题是一样的，解法也是一样的；  
公共子序列不是公共子串，不要求连续，但是顺序不能变，因此最长的公共子序列也就是最多不相交线的数量

In [6]:
text1 = "abewdewcde"
text2 = "acassddde"

dp = [[0 for i in range(len(text2)+1)] for j in range(len(text1)+1)]
for i in range(len(text1)-1,-1,-1):
    for j in range(len(text2)-1,-1,-1):
        if text1[i]==text2[j]:
            dp[i][j] = dp[i+1][j+1]+1
        else:
            dp[i][j] = max(dp[i+1][j],dp[i][j+1])
print(dp[0][0])

4
